### ISSUE TITLE
Code Review by Luis Rivas

### ISSUE THREAD

**Issue by Lnrivas** [KyleWynne/Health_Blocks#3]
Hey team, this is a very impressive project, good job! I only have a few minor edits to suggest. 

When I was going through it all, I noticed the instructions in the README for building the test blocks were unclear. It does not specify what block to insert into the calorie sum block as inputs. I assume it is the calorie intake block that goes into it twice. I cleared this up in my PR. 

I also added a new button to run the javascript directly from your website, since it can be a hassle to rely solely on exporting the code and figuring out how to run it elsewhere. This is also included in my PR.

**Comment by KyleWynne** [comment]
Thank you for your contribution and your feedback luis.

Thank you for bringing up the instructions we'll make sure to double back and make sure those are as clear as possible.

Thank you for the run code button aswell we were having issues with the run code button giving us an object promise so hopefully this can fix that
